PLACEHOLDER_FEATURED_MOVIES = [
    {
        "id": 101,
        "tmdbId": None,
        "movieLensId": None,
        "imdbId": None,
        "title": "Star Wars",
        "originalTitle": "Star Wars",
        "year": 1977,
        "overview": "A young hero joins a space adventure that mixes mystery, teamwork, and rebellion.",
        "posterUrl": None,
        "genres": ["Adventure", "Sci-Fi"],
        "tags": ["adventure", "friendship", "sci-fi"],
        "coverage": {
            "availableForContent": True,
            "availableForCollaborative": True,
            "contentCoverage": 0.94,
            "collaborativeCoverage": 0.91,
            "coverageNotes": ["Strong content metadata", "Strong collaborative history"],
        },
    },
    {
        "id": 102,
        "tmdbId": None,
        "movieLensId": None,
        "imdbId": None,
        "title": "The Lord of the Rings: The Fellowship of the Ring",
        "originalTitle": "The Lord of the Rings: The Fellowship of the Ring",
        "year": 2001,
        "overview": "A fantasy journey where friendship and courage guide a dangerous quest.",
        "posterUrl": None,
        "genres": ["Adventure", "Fantasy"],
        "tags": ["magic", "friendship", "adventure"],
        "coverage": {
            "availableForContent": True,
            "availableForCollaborative": True,
            "contentCoverage": 0.95,
            "collaborativeCoverage": 0.88,
            "coverageNotes": ["Rich genre and tag metadata", "Well-covered by collaborative signals"],
        },
    },
    {
        "id": 103,
        "tmdbId": None,
        "movieLensId": None,
        "imdbId": None,
        "title": "Harry Potter and the Sorcerer's Stone",
        "originalTitle": "Harry Potter and the Sorcerer's Stone",
        "year": 2001,
        "overview": "A student discovers a hidden magical world shaped by puzzles, danger, and friendship.",
        "posterUrl": None,
        "genres": ["Fantasy", "Adventure"],
        "tags": ["magic", "friendship", "mystery"],
        "coverage": {
            "availableForContent": True,
            "availableForCollaborative": False,
            "contentCoverage": 0.93,
            "collaborativeCoverage": 0.34,
            "coverageNotes": ["Strong content metadata", "Sparse collaborative placeholder coverage"],
        },
    },
    {
        "id": 104,
        "tmdbId": None,
        "movieLensId": None,
        "imdbId": None,
        "title": "Toy Story",
        "originalTitle": "Toy Story",
        "year": 1995,
        "overview": "A group of animated toys balances comedy, friendship, and family adventure.",
        "posterUrl": None,
        "genres": ["Animation", "Comedy", "Family"],
        "tags": ["animation", "friendship", "family", "comedy"],
        "coverage": {
            "availableForContent": True,
            "availableForCollaborative": True,
            "contentCoverage": 0.9,
            "collaborativeCoverage": 0.9,
            "coverageNotes": ["Balanced content metadata", "Balanced collaborative placeholder coverage"],
        },
    },
    {
        "id": 105,
        "tmdbId": None,
        "movieLensId": None,
        "imdbId": None,
        "title": "Back to the Future",
        "originalTitle": "Back to the Future",
        "year": 1985,
        "overview": "A playful time-travel story driven by sci-fi ideas, comedy, and adventure.",
        "posterUrl": None,
        "genres": ["Adventure", "Comedy", "Sci-Fi"],
        "tags": ["sci-fi", "adventure", "comedy"],
        "coverage": {
            "availableForContent": True,
            "availableForCollaborative": True,
            "contentCoverage": 0.92,
            "collaborativeCoverage": 0.87,
            "coverageNotes": ["Rich tag coverage", "Strong collaborative placeholder coverage"],
        },
    },
    {
        "id": 106,
        "tmdbId": None,
        "movieLensId": None,
        "imdbId": None,
        "title": "Iron Man",
        "originalTitle": "Iron Man",
        "year": 2008,
        "overview": "A fast-moving superhero origin story mixing technology, action, and humor.",
        "posterUrl": None,
        "genres": ["Action", "Sci-Fi"],
        "tags": ["superheroes", "sci-fi", "comedy"],
        "coverage": {
            "availableForContent": False,
            "availableForCollaborative": True,
            "contentCoverage": 0.29,
            "collaborativeCoverage": 0.89,
            "coverageNotes": ["Thin content placeholder metadata", "Strong collaborative history"],
        },
    },
    {
        "id": 107,
        "tmdbId": None,
        "movieLensId": None,
        "imdbId": None,
        "title": "Finding Nemo",
        "originalTitle": "Finding Nemo",
        "year": 2003,
        "overview": "An underwater family adventure focused on courage, humor, and friendship.",
        "posterUrl": None,
        "genres": ["Animation", "Adventure", "Family"],
        "tags": ["animation", "family", "adventure", "friendship"],
        "coverage": {
            "availableForContent": True,
            "availableForCollaborative": False,
            "contentCoverage": 0.91,
            "collaborativeCoverage": 0.31,
            "coverageNotes": ["Strong content metadata", "Limited collaborative placeholder coverage"],
        },
    },
    {
        "id": 108,
        "tmdbId": None,
        "movieLensId": None,
        "imdbId": None,
        "title": "The Princess Bride",
        "originalTitle": "The Princess Bride",
        "year": 1987,
        "overview": "A light fantasy adventure with romance, comedy, and memorable teamwork.",
        "posterUrl": None,
        "genres": ["Adventure", "Comedy", "Fantasy"],
        "tags": ["adventure", "magic", "comedy", "friendship"],
        "coverage": {
            "availableForContent": True,
            "availableForCollaborative": True,
            "contentCoverage": 0.88,
            "collaborativeCoverage": 0.73,
            "coverageNotes": ["Good tag coverage", "Moderate collaborative placeholder coverage"],
        },
    },
    {
        "id": 109,
        "tmdbId": None,
        "movieLensId": None,
        "imdbId": None,
        "title": "Interstellar",
        "originalTitle": "Interstellar",
        "year": 2014,
        "overview": "A large-scale science-fiction journey that emphasizes exploration, risk, and family bonds.",
        "posterUrl": None,
        "genres": ["Adventure", "Drama", "Sci-Fi"],
        "tags": ["sci-fi", "adventure", "family", "mystery"],
        "coverage": {
            "availableForContent": True,
            "availableForCollaborative": True,
            "contentCoverage": 0.9,
            "collaborativeCoverage": 0.85,
            "coverageNotes": ["Strong genre metadata", "Strong collaborative placeholder coverage"],
        },
    },
    {
        "id": 110,
        "tmdbId": None,
        "movieLensId": None,
        "imdbId": None,
        "title": "Spider-Man: Into the Spider-Verse",
        "originalTitle": "Spider-Man: Into the Spider-Verse",
        "year": 2018,
        "overview": "A colorful superhero adventure centered on growth, teamwork, and alternate worlds.",
        "posterUrl": None,
        "genres": ["Action", "Adventure", "Animation"],
        "tags": ["superheroes", "animation", "adventure", "family"],
        "coverage": {
            "availableForContent": True,
            "availableForCollaborative": True,
            "contentCoverage": 0.94,
            "collaborativeCoverage": 0.86,
            "coverageNotes": ["Rich tag and genre metadata", "Strong collaborative placeholder coverage"],
        },
    },
]

PLACEHOLDER_RECOMMENDATION_CANDIDATES = [
    {
        "id": 201,
        "tmdbId": None,
        "movieLensId": None,
        "imdbId": None,
        "title": "The Matrix",
        "originalTitle": "The Matrix",
        "year": 1999,
        "overview": "A high-energy sci-fi action story about hidden systems, discovery, and resistance.",
        "posterUrl": None,
        "genres": ["Action", "Sci-Fi"],
        "tags": ["sci-fi", "mystery", "adventure"],
        "coverage": {
            "availableForContent": True,
            "availableForCollaborative": True,
            "contentCoverage": 0.91,
            "collaborativeCoverage": 0.89,
            "coverageNotes": ["Strong content metadata", "Strong collaborative history"],
        },
    },
    {
        "id": 202,
        "tmdbId": None,
        "movieLensId": None,
        "imdbId": None,
        "title": "Shrek",
        "originalTitle": "Shrek",
        "year": 2001,
        "overview": "A comic fairy-tale adventure about unlikely friendship and playful fantasy.",
        "posterUrl": None,
        "genres": ["Animation", "Adventure", "Comedy"],
        "tags": ["animation", "comedy", "friendship", "magic"],
        "coverage": {
            "availableForContent": True,
            "availableForCollaborative": True,
            "contentCoverage": 0.89,
            "collaborativeCoverage": 0.84,
            "coverageNotes": ["Strong content metadata", "Strong collaborative placeholder coverage"],
        },
    },
    {
        "id": 203,
        "tmdbId": None,
        "movieLensId": None,
        "imdbId": None,
        "title": "The Avengers",
        "originalTitle": "The Avengers",
        "year": 2012,
        "overview": "A team-up blockbuster driven by superheroes, action, and large-scale collaboration.",
        "posterUrl": None,
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "tags": ["superheroes", "adventure", "comedy"],
        "coverage": {
            "availableForContent": False,
            "availableForCollaborative": True,
            "contentCoverage": 0.27,
            "collaborativeCoverage": 0.9,
            "coverageNotes": ["Limited content placeholder metadata", "Strong collaborative history"],
        },
    },
    {
        "id": 204,
        "tmdbId": None,
        "movieLensId": None,
        "imdbId": None,
        "title": "The Lion King",
        "originalTitle": "The Lion King",
        "year": 1994,
        "overview": "A family adventure about growth, loyalty, and responsibility with strong emotional themes.",
        "posterUrl": None,
        "genres": ["Adventure", "Animation", "Family"],
        "tags": ["animation", "family", "friendship", "adventure"],
        "coverage": {
            "availableForContent": True,
            "availableForCollaborative": False,
            "contentCoverage": 0.92,
            "collaborativeCoverage": 0.33,
            "coverageNotes": ["Strong content metadata", "Limited collaborative placeholder coverage"],
        },
    },
    {
        "id": 205,
        "tmdbId": None,
        "movieLensId": None,
        "imdbId": None,
        "title": "Black Panther",
        "originalTitle": "Black Panther",
        "year": 2018,
        "overview": "A superhero story mixing technology, leadership, and large-scale action.",
        "posterUrl": None,
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "tags": ["superheroes", "adventure", "sci-fi"],
        "coverage": {
            "availableForContent": True,
            "availableForCollaborative": True,
            "contentCoverage": 0.82,
            "collaborativeCoverage": 0.86,
            "coverageNotes": ["Good genre metadata", "Strong collaborative placeholder coverage"],
        },
    },
    {
        "id": 206,
        "tmdbId": None,
        "movieLensId": None,
        "imdbId": None,
        "title": "Spirited Away",
        "originalTitle": "Spirited Away",
        "year": 2001,
        "overview": "A fantasy coming-of-age journey full of mystery, magic, and changing worlds.",
        "posterUrl": None,
        "genres": ["Animation", "Adventure", "Fantasy"],
        "tags": ["animation", "magic", "mystery", "adventure"],
        "coverage": {
            "availableForContent": True,
            "availableForCollaborative": True,
            "contentCoverage": 0.93,
            "collaborativeCoverage": 0.72,
            "coverageNotes": ["Rich tag metadata", "Moderate collaborative placeholder coverage"],
        },
    },
    {
        "id": 207,
        "tmdbId": None,
        "movieLensId": None,
        "imdbId": None,
        "title": "Big Hero 6",
        "originalTitle": "Big Hero 6",
        "year": 2014,
        "overview": "A family-friendly superhero adventure combining invention, humor, and teamwork.",
        "posterUrl": None,
        "genres": ["Action", "Adventure", "Animation"],
        "tags": ["superheroes", "animation", "friendship", "family"],
        "coverage": {
            "availableForContent": True,
            "availableForCollaborative": False,
            "contentCoverage": 0.88,
            "collaborativeCoverage": 0.28,
            "coverageNotes": ["Strong content placeholder metadata", "Limited collaborative placeholder coverage"],
        },
    },
]
